# Generated by Django 5.0.6 on 2026-07-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный расчёт')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_receipt_no', models.CharField(blank=True, max_length=30)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_at'],
            },
        ),
    ]
