# Generated by Django 5.0.6 on 2026-07-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Номер рейса')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('departure_time', models.TimeField(verbose_name='Время вылета')),
                ('arrival_time', models.TimeField(verbose_name='Время прилёта')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('departed', 'Вылетел'), ('cancelled', 'Отменён')], default='scheduled', max_length=20)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='references.aircrafttype')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='references.direction')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('travel_class', models.CharField(max_length=20, verbose_name='Класс')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('blocked', 'Забронировано временно'), ('sold', 'Продано')], default='free', max_length=20)),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Блокировка до')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_seats', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'unique_together': {('flight', 'seat_number')},
            },
        ),
    ]
