# Generated by Django 5.0.6 on 2026-07-29 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=20)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('z_report_number', models.CharField(blank=True, max_length=20)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'ordering': ['-open_time'],
            },
        ),
    ]
