# Generated by Django 5.0.6 on 2026-07-29 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('passengers', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер брони')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('baggage_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='passengers.passenger')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='flights.seat')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='references.tariff')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
