# Generated by Django 5.0.6 on 2026-07-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('plane', 'Самолёт'), ('helicopter', 'Вертолёт')], max_length=20, verbose_name='Категория')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость')),
                ('max_baggage_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Макс. вес багажа, кг')),
            ],
            options={
                'verbose_name': 'Тип ВС',
                'verbose_name_plural': 'Типы ВС',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Код ИАТА')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField(verbose_name='Расстояние, км')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='references.airport', verbose_name='Аэропорт прибытия')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='references.airport', verbose_name='Аэропорт отправления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_class', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес')], max_length=20, verbose_name='Класс')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая стоимость')),
                ('refund_penalty_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% штрафа за возврат')),
                ('refundable', models.BooleanField(default=True, verbose_name='Возвратность')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
                ('valid_to', models.DateField(verbose_name='Дата окончания действия')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='references.aircrafttype')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='references.direction')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.CheckConstraint(check=models.Q(('departure_airport', models.F('arrival_airport')), _negated=True), name='departure_ne_arrival'),
        ),
    ]
